title: Vic's Learning Notes
description: 一個新手小白的血路歷程!
theme: just-the-docs
color_scheme: dark

url: https://vicmeng-jpg.github.io/VIC

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
