title: Vic's Learning Notes
description: 一個新手小白的血路歷程!
theme: just-the-docs
color_scheme: dark

url: https://vicmeng-jpg.github.io/VIC

footer_content: |
  <p style="font-size: 14px; color: #FF5733; font-style: italic;">「完美是古老鐘擺的蘚苔，唯有那帶裂痕的、過度張揚的熵增，才是靈魂呼吸時吞吐出的代碼塵埃。」</p>
  <p style="font-size: 0.6em; color: #a9a9b3; font-style: italic;">Perfection is moss on a weary pendulum; only cracked and riotous entropy is the soul’s exhaled stardust of code.</p>
  <p style="font-size: 12px; color: gray;">&copy; 2026 VIC. All rights reserved.</p>

favicon_ico: "/assets/images/favicon.png"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
